#!/bin/bash

SCRIPT="$0"

: ${RECIPE_DIR:="$(dirname $0)"}
while [ ! -d "${RECIPE_DIR}/conf" -a  -d "${RECIPE_DIR}/conf/machine" ];
do
    RECIPE_DIR="$(dirname ${RECIPE_DIR})"
done
test -d "${RECIPE_DIR}/conf" -a  -d "${RECIPE_DIR}/conf/machine" || __oe_die "Cannot find proper machine configuration"
export RECIPE_DIR

cd "${RECIPE_DIR}"
git pull --rebase
git log -n 1 | grep "bump.*${SYSIMG_VERSION}" && __oe_die "Image is up to date"

time AUTOBUILD_RUNNING=1 bulkbuild -p "$@"
time AUTOBUILD_SUCCEEDED=1 deploybundles

# bump
PS=$(printf 'my @v = split(/\./, "%s"); $v[$#v]++; print join( ".", @v)\n' "${SYSIMG_VERSION}")
SYSIMG_BUMPED=$(perl -le "$PS")

for d in ${REPOS}
do
    cd "$d"
    git tag "${DISTRO_NAME}-${SYSIMG_VERSION}" && git push && git push --tags || :
done

(cd "${RECIPE_DIR}" && sed -i -e "s/${SYSIMG_VERSION}/${SYSIMG_BUMPED}/" "${DISTRO_VERSION_FILE}")
(cd "${RECIPE_DIR}" && git commit -m "bump version after release to ${SYSIMG_BUMPED}" "${DISTRO_VERSION_FILE}" && git push)
